### ISSUE TITLE
addRenderEventListener not executed when MarkerArea contain Text with &nbsp;

### ISSUE THREAD

**Issue by chintan08-tops** [ailon/markerjs2#59] opened 2021-11-01 13:15 UTC
While I Edit the image and add some Text using text tool and did the copy paste some code from the written paragraph sometime `&nbsp; `is added and that time my addRenderEventListener is now executed.

Please let me know if anyone have the solution.

**Comment by ailon** [comment] 2021-11-02 06:45
What version are you using? This was fixed in [v2.8.4](https://github.com/ailon/markerjs2/blob/master/CHANGELOG.md#284---2021-07-05).

In case you are using a new version, and this still happens, please provide some more details (OS, browser, ideally - a repro). Thanks!

**Comment by chintan08-tops** [comment] 2021-11-02 07:17
"markerjs2": "^2.14.1"

using this version in my react application.

OS - Windows 
Browser - Google Chrome

**Comment by ailon** [comment] 2021-11-02 07:19
Any way you can share the text you trying to paste that results in this behavior?

**Comment by chintan08-tops** [comment] 2021-11-02 07:33
I have just edit my previous comment in which I added steps to recreate the issue.

Thanks.

**Comment by ailon** [comment] 2021-11-02 07:52
Hmm... still works for me. I will try to play some more to see if I can reproduce it.

**Comment by ailon** [comment] 2022-01-14 09:34
Version 2.18 now converts pasted content to plain text which hopefully fixes this issue as well.

**Closed by ailon** 2022-01-14 09:34 UTC
